### ISSUE TITLE
website: build broken with vendored google.golang.org/cloud/datastore

### ISSUE THREAD

**Issue by edrex** [camlistore/camlistore#743]
```
> cd ./website/
> go build
package camlistore.org/website
	imports google.golang.org/cloud/datastore
	imports google.golang.org/cloud/datastore/internal/proto: use of internal package not allowed
> git checkout 219f966a959696e9a0bd2c2212e67edace288c3f~ ../vendor/google.golang.org/cloud/
> go build # succeeds
```

broken from 219f966a959696e9a0bd2c2212e67edace288c3f

@willnorris wondering what version of google.golang.org/cloud/datastore you have in your GOPATH

@mpl

**Comment by willnorris** [comment]
yeah, I'm seeing the same error.  Updating the vendored copies of `google.golang.org/grpc`, `google.golang.org/cloud` and `github.com/golang/protobuf` to the latest version of each (and fixing a few build failures) fixes the compilation errors for camweb, but I haven't fully tested to verify that everything else is still working as expected.

**Comment by edrex** [comment]
ok cool, I didn't get past the build failures when I tried updating the deps
